-- MySQL Script generated by MySQL Workbench
-- Sun Aug 22 00:25:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`hibernate_sequence` (
    `next_val` BIGINT NULL DEFAULT NULL)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`users` (
                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                `email` VARCHAR(50) NULL DEFAULT NULL,
                                                `password` VARCHAR(120) NULL DEFAULT NULL,
                                                `username` VARCHAR(20) NULL DEFAULT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE,
                                                UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`refreshtoken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`refreshtoken` (
                                                       `id` BIGINT NOT NULL,
                                                       `expiry_date` DATETIME NOT NULL,
                                                       `token` VARCHAR(255) NOT NULL,
                                                       `user_id` BIGINT NULL DEFAULT NULL,
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE INDEX `UK_or156wbneyk8noo4jstv55ii3` (`token` ASC) VISIBLE,
                                                       INDEX `FKa652xrdji49m4isx38pp4p80p` (`user_id` ASC) VISIBLE,
                                                       CONSTRAINT `FKa652xrdji49m4isx38pp4p80p`
                                                           FOREIGN KEY (`user_id`)
                                                               REFERENCES `testdb`.`users` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`roles` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `name` VARCHAR(20) NULL DEFAULT NULL,
                                                PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `testdb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`user_roles` (
                                                     `user_id` BIGINT NOT NULL,
                                                     `role_id` INT NOT NULL,
                                                     PRIMARY KEY (`user_id`, `role_id`),
                                                     INDEX `FKh8ciramu9cc9q3qcqiv4ue8a6` (`role_id` ASC) VISIBLE,
                                                     CONSTRAINT `FKh8ciramu9cc9q3qcqiv4ue8a6`
                                                         FOREIGN KEY (`role_id`)
                                                             REFERENCES `testdb`.`roles` (`id`),
                                                     CONSTRAINT `FKhfh9dx7w3ubf1co1vdev94g3f`
                                                         FOREIGN KEY (`user_id`)
                                                             REFERENCES `testdb`.`users` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
